[providers]
node = true

[setup]
pkgs = ["pnpm-10_x", "nodejs_20"]

[phases.install]
cmds = ["pnpm install --frozen-lockfile"]

[phases.build]
cmds = ["pnpm run build:no-typecheck"]

[start]
cmd = "node --enable-source-maps ./backend/dist/index.mjs"
