import { Helmet } from "react-helmet-async";
import { Link } from "wouter";
import { ArrowLeft } from "lucide-react";
import { Logo } from "@/components/layout/Logo";

export default function TermsAndConditions() {
  return (
    <div className="min-h-screen bg-[#060312] text-foreground font-sans">
      <Helmet>
        <title>Terms & Conditions | GrowFlow AI</title>
        <meta name="description" content="Read the Terms and Conditions of using GrowFlow AI." />
      </Helmet>
      
      <div className="max-w-3xl mx-auto px-6 py-12">
        <div className="mb-10">
          <Link href="/">
            <div className="cursor-pointer"><Logo size="md" /></div>
          </Link>
        </div>

        <Link href="/">
          <span className="inline-flex items-center gap-1.5 text-sm text-white/40 hover:text-white/70 transition-colors mb-8 cursor-pointer">
            <ArrowLeft className="w-4 h-4" /> Back to home
          </span>
        </Link>

        <div className="prose prose-invert max-w-3xl mx-auto px-4 py-12">
          <h1 className="text-4xl font-bold text-white mb-2">Terms & Conditions</h1>
          <p className="text-white/40 text-sm mb-10">Last updated: May 2026</p>

          <div className="space-y-10 text-white/80 leading-relaxed">
            <section>
              <h2 className="text-2xl font-semibold text-white mb-4">1. Acceptance of Terms</h2>
              <p>
                By accessing or using GrowFlow AI ("the Service"), operated by GrowFlow AI ("we," "us," or "our"), you agree to be bound by these Terms and Conditions. If you disagree with any part of the terms, you do not have permission to access the Service.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-white mb-4">2. Description of Service</h2>
              <p>
                GrowFlow AI is an artificial intelligence-powered content generation platform designed to help creators, marketers, and businesses generate social media content, strategies, and performance predictions. We utilize advanced Large Language Models (LLMs) to provide these services.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-white mb-4">3. User Accounts and Registration</h2>
              <p>
                To use most features of the Service, you must register for an account using Clerk authentication. You are responsible for maintaining the confidentiality of your account and password. You agree to accept responsibility for all activities that occur under your account.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-white mb-4">4. Subscription Plans and Payment</h2>
              <p>
                We offer various subscription tiers (Starter, Creator, Infinity) as well as one-time credit top-ups. Payments are processed securely via <strong>Razorpay</strong>. 
              </p>
              <ul className="list-disc pl-6 space-y-2">
                <li>Pricing is listed in Indian Rupees (INR) and other supported currencies.</li>
                <li>Subscriptions auto-renew at the end of each billing cycle (monthly or yearly) unless cancelled.</li>
                <li>You authorize us to charge your chosen payment provider for these recurring fees.</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-white mb-4">5. Refund Policy</h2>
              <p>
                We offer a <strong>7-day money-back guarantee</strong> for first-time paid subscribers. If you are not satisfied with the service within the first 7 days of your initial subscription, you may request a full refund, provided you have used fewer than 50 generations. For more details, see our <Link href="/refund-policy" className="text-cyan-400 hover:underline">Refund Policy</Link>.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-white mb-4">6. Intellectual Property</h2>
              <p>
                <strong>Your Content:</strong> You retain full ownership of the raw inputs you provide and the specific content generated by the AI for your account. You grant us a limited license to process this content to provide the Service.
              </p>
              <p>
                <strong>Our Property:</strong> The GrowFlow AI platform, including its software, design, logos, and original code, is the exclusive property of GrowFlow AI and is protected by intellectual property laws.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-white mb-4">7. Prohibited Uses</h2>
              <p>You agree not to use the Service to:</p>
              <ul className="list-disc pl-6 space-y-2">
                <li>Generate or spread spam, malware, or deceptive content.</li>
                <li>Create content that promotes hate speech, violence, or discrimination.</li>
                <li>Impersonate individuals or organizations without authorization.</li>
                <li>Attempt to reverse engineer or scrape the platform.</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-white mb-4">8. Limitation of Liability</h2>
              <p>
                GrowFlow AI provides tools based on artificial intelligence. While we strive for high quality, AI can generate inaccurate or biased information. We are not liable for any damages resulting from your use of the content generated, including business losses or reputational damage.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-white mb-4">9. Governing Law</h2>
              <p>
                These Terms shall be governed by and construed in accordance with the laws of <strong>India</strong>. Any disputes arising under these terms shall be subject to the exclusive jurisdiction of the courts in <strong>West Bengal, India</strong>.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-white mb-4">10. Contact Information</h2>
              <p>
                If you have any questions about these Terms, please contact us at:
                <br />
                <a href="mailto:growflowhelp@gmail.com" className="text-cyan-400 font-medium hover:underline">growflowhelp@gmail.com</a>
              </p>
            </section>
          </div>

          <div className="mt-20 pt-8 border-t border-white/10 flex flex-col md:flex-row items-center justify-between text-[13px] text-white/30 gap-4">
            <span>© 2026 GrowFlow AI. All rights reserved.</span>
            <div className="flex items-center gap-6">
              <Link href="/terms-and-conditions"><span className="hover:text-white/60 transition-colors cursor-pointer">Terms of Service</span></Link>
              <Link href="/privacy-policy"><span className="hover:text-white/60 transition-colors cursor-pointer">Privacy Policy</span></Link>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
