import { Router, type IRouter } from "express";
import healthRouter from "./health";
import contentRouter from "./content";
import hooksRouter from "./hooks";
import subscriptionRouter from "./subscription";
import ideasRouter from "./ideas";
import strategyRouter from "./strategy";
import supportRouter from "./support";
import settingsRouter from "./settings";
import favoritesRouter from "./favorites";
import referralRouter from "./referral";
import trendsRouter from "./trends";
import improveCompetitorRouter from "./improve-competitor";
import earlyAccessRouter from "./early-access";
import bioRouter from "./bio";
import captionRouter from "./caption";
import dailyRouter from "./daily";
import contentPackRouter from "./content-pack";
import statsRouter from "./stats";
import feedbackRouter from "./feedback";
import adminRouter from "./admin";
import authRouter from "./auth";
import calendarRouter from "./calendar";
import repurposeRouter from "./repurpose";
import announcementRouter from "./announcement";
import paymentRouter from "./payment";
import coachRouter from "./coach";
import vaultRouter from "./vault";
import ghostwriterRouter from "./ghostwriter";
import predictorRouter from "./predictor";
import hashtagRouter from "./hashtags";
import hookScorerRouter from "./hook-scorer";
import abTestRouter from "./ab-test";
import trendAlertsRouter from "./trend-alerts";
import trialRouter from "./trial";
import userRouter from "./user";

const router: IRouter = Router();

router.use(healthRouter);
router.use("/subscription", subscriptionRouter);
router.use("/content", contentRouter);
router.use("/hooks", hooksRouter);
router.use("/ideas", ideasRouter);
router.use("/strategy", strategyRouter);
router.use("/support", supportRouter);
router.use("/settings", settingsRouter);
router.use("/favorites", favoritesRouter);
router.use("/referral", referralRouter);
router.use("/trends", trendsRouter);
router.use("/improve-competitor", improveCompetitorRouter);
router.use("/early-access", earlyAccessRouter);
router.use("/bio", bioRouter);
router.use("/caption", captionRouter);
router.use("/daily", dailyRouter);
router.use("/content-pack", contentPackRouter);
router.use("/stats", statsRouter);
router.use("/feedback", feedbackRouter);
router.use("/admin", adminRouter);
router.use("/auth", authRouter);
router.use("/calendar", calendarRouter);
router.use("/repurpose", repurposeRouter);
router.use("/announcement", announcementRouter);
router.use("/payment", paymentRouter);
router.use("/coach", coachRouter);
router.use("/vault", vaultRouter);
router.use("/ghostwriter", ghostwriterRouter);
router.use("/predictor", predictorRouter);
router.use("/hashtags", hashtagRouter);
router.use("/hook-scorer", hookScorerRouter);
router.use("/ab-test", abTestRouter);
router.use("/trend-alerts", trendAlertsRouter);
router.use("/trial", trialRouter);
router.use("/user", userRouter);

export default router;
