import { Router, type IRouter } from "express";
import healthRouter from "./health";
import contentRouter from "./content";
import hooksRouter from "./hooks";
import subscriptionRouter from "./subscription";
import ideasRouter from "./ideas";
import strategyRouter from "./strategy";
import supportRouter from "./support";
import settingsRouter from "./settings";
import favoritesRouter from "./favorites";
import referralRouter from "./referral";
import trendsRouter from "./trends";
import improveCompetitorRouter from "./improve-competitor";
import earlyAccessRouter from "./early-access";
import bioRouter from "./bio";
import captionRouter from "./caption";
import dailyRouter from "./daily";
import contentPackRouter from "./content-pack";
import statsRouter from "./stats";
import feedbackRouter from "./feedback";
import adminRouter from "./admin";
import authRouter from "./auth";
import calendarRouter from "./calendar";
import repurposeRouter from "./repurpose";
import announcementRouter from "./announcement";

const router: IRouter = Router();

router.use(healthRouter);
router.use(subscriptionRouter);
router.use(contentRouter);
router.use(hooksRouter);
router.use(ideasRouter);
router.use(strategyRouter);
router.use(supportRouter);
router.use(settingsRouter);
router.use(favoritesRouter);
router.use(referralRouter);
router.use(trendsRouter);
router.use(improveCompetitorRouter);
router.use(earlyAccessRouter);
router.use(bioRouter);
router.use(captionRouter);
router.use(dailyRouter);
router.use(contentPackRouter);
router.use(statsRouter);
router.use(feedbackRouter);
router.use(adminRouter);
router.use(authRouter);
router.use(calendarRouter);
router.use(repurposeRouter);
router.use(announcementRouter);

export default router;
